### ISSUE TITLE
jsonrpc4j to support Spring Boot v3.x

### ISSUE THREAD

**Issue by vikinatora** [LimeChain/Fruzhin#28]
Use latest 3.x version of Spring Boot. Currently we use v2.7.3 because 3.x fails to build with jsonrpc4j.
See: https://stackoverflow.com/questions/74760350/application-fails-on-run-in-a-new-release-of-springboot-3-0-0.
There's an active issue an it seems that this guy is going to make a PR(it won't be his first one): https://github.com/briandilley/jsonrpc4j/issues/303

**Comment by David-Petrov** [comment]
Seems [_a_ PR](https://github.com/briandilley/jsonrpc4j/pull/312) was opened, but never merged... However, there [exists a fork](https://github.com/Lendico/jsonrpc4j/pull/1) which claims to have solved this. Maybe take a fresher look at this?

**Comment by reneleonhardt** [comment]
@vikinatora @David-Petrov the PR has been merged and a new version 1.7 has been released in case you still need it 😄
